// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMwjP4ohGk9E01SE_sXlUkrwTPynVwrTw',
    appId: '1:82532282878:web:b7be5e9f0c4c968e54d0af',
    messagingSenderId: '82532282878',
    projectId: 'news-617c7',
    authDomain: 'news-617c7.firebaseapp.com',
    storageBucket: 'news-617c7.appspot.com',
    measurementId: 'G-EQKXNYXX37',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAdFjsOIjQ3PIaPwWzTWXEH9fJyVqyefo',
    appId: '1:82532282878:android:466f22df8185a1bf54d0af',
    messagingSenderId: '82532282878',
    projectId: 'news-617c7',
    storageBucket: 'news-617c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCWk7J76MT8c_TafZOdOdx7hsu2hu2KNM',
    appId: '1:82532282878:ios:6f774b92d15bf01654d0af',
    messagingSenderId: '82532282878',
    projectId: 'news-617c7',
    storageBucket: 'news-617c7.appspot.com',
    androidClientId: '82532282878-i004fbjd11sufl2asanpoffkrupea2dm.apps.googleusercontent.com',
    iosClientId: '82532282878-cvjg7uqpg0k2gp2prfbikf5sl7tqcdql.apps.googleusercontent.com',
    iosBundleId: 'com.ashmawi.news',
  );
}
